port_names = {
	[17] = { -- Hideout Helm
		[0x58] = "Crown Door Room",
		[0x59] = "Entrance",
	},
	[20] = { -- Llama Temple
		[0x4E] = "Outside Matching Game",
		[0x58] = "Entrance (Left)",
		[0x99] = "Lava Room",
		[0x9A] = "Entrance (Right)",
	},
	[26] = { -- Factory
		[0x7D] = "Lobby (Left)",
		[0xD9] = "Lobby (Far)",
		[0xEE] = "Funky's",
		[0x105] = "Production Room (Lower)",
		[0x10B] = "Arcade Table",
		[0x10C] = "Production Room (Higher)",
		[0x141] = "Lobby (Right)",
		[0x142] = "Storage Room",
		[0x143] = "Snide's",
		[0x144] = "Research & Development",
	},
	[30] = { -- Galleon
		[0x15] = "Near the Cactus",
		[0x16] = "Lighthouse Side (Near Rocketbarrel)",
		[0x55] = "Gold Tower",
		[0x56] = "Near Seal Race",
		[0x5F] = "On Metal Crate",
		[0x60] = "On Rafters",
		[0x66] = "Outside Snide's",
		[0x6C] = "Near 2-Door Ship",
		[0x1F6] = "Back of Lighthouse",
		[0x1F7] = "Entrance Intersection",
	},
	[34] = { -- Isles
		[0x10] = "Ring (Far Left)",
		[0x11] = "Outside K. Lumsy's Prison",
		[0x12] = "Ring (Far Right)",
		[0x13] = "Outside Angry Aztec Lobby",
		[0x14] = "Waterfall Pool",
		[0x15] = "Ring (Middle Left)",
		[0x16] = "Ring (Middle Right)",
		[0x17] = "Ring (Near)",
		[0x18] = "Outside Frantic Factory Lobby",
		[0x19] = "Outside Banana Fairy Island",

	},
	[38] = { -- Aztec
		[0x6] = "Level Entrance",
		[0x7] = "Outside Candy's",
		[0x73] = "Tunnel Exit (Far Right)",
		[0x7F] = "Tunnel Exit (Near)",
		[0x80] = "Outside Tiny Temple",
		[0x82] = "Near Snide's",
		[0x87] = "Sand Tunnel",
		[0x95] = "Outside Cranky's",
		[0x98] = "Tunnel Exit (Far Left)",
		[0xB1] = "Outside Funky's",
	},
	[48] = { -- Fungi
		[0x35] = "Outside Mill",
		[0x36] = "Clock (Near Blue Tunnel)",
		[0x49] = "Clock (Near Green Tunnel)",
		[0x4A] = "Outside Funky's",
		[0x4B] = "Clock (Near Magenta Tunnel)",
		[0x4E] = "Outside Giant Mushroom Entrance",
		[0x4F] = "Clock (Near Well)",
		[0x51] = "Owl Tree",
		[0x55] = "Giant Mushroom (Lower Grass)",
		[0x56] = "Giant Mushroom (Upper Balcony)",

	},
	[72] = { -- Caves
		[0x21] = "Outside 5-Door Igloo (Right)",
		[0x22] = "Entrance (Right)",
		[0x36] = "Outside Rotating Room",
		[0x37] = "Entrance (Left)",
		[0x56] = "Hidden Bonus Room",
		[0x57] = "Outside 5-Door Igloo (Centre)",
		[0x60] = "On 5-Door Cabin",
		[0x6A] = "Hidden Monkeyport Room",
		[0x6B] = "Water Pillar",
		[0xB5] = "Lone Platform",
	},
	[87] = { -- Castle
		[0x21] = "Pool (Centre-Right)",
		[0x22] = "Back of Castle",
		[0x23] = "Outside Cranky's",
		[0x24] = "Pool (Left-most)",
		[0x28] = "Near Upper Rocketbarrel",
		[0x29] = "Outside Greenhouse",
		[0x2A] = "Top of the Castle",
		[0x2B] = "Pool (Centre-Left)",
		[0x2C] = "Pool (Centre)",
		[0x2D] = "Pool (Right-most)",
	},
	[97] = { -- KLumsy
		[0x9] = "Fake Bananaport",
	},
	[112] = { -- Castle DDC Crypt
		[0x18] = "Entrance (Left)",
		[0x19] = "Entrance (Centre)",
		[0x1A] = "Entrance (Right)",
		[0x1B] = "Outside Chunky's Room",
		[0x1C] = "Outside DK's Room",
		[0x1D] = "Outside Diddy's Room",
	},
	[170] = { -- Helm Lobby
		[0x8] = "Entrance",
		[0x9] = "Near Level Entry",
	},
}